# ======================== 开发环境 ========================
spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/hify_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/hify_dev
      username: hify
      password: hify

  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  port: 8080

logging:
  level:
    com.hify: debug
    org.apache.ibatis: debug
