apiVersion: v1
kind: Service
metadata:
  name: hify-frontend
  namespace: hify
  labels:
    app: hify-frontend
spec:
  type: NodePort
  selector:
    app: hify-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
