apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hify-prometheus-data
  namespace: hify
  labels:
    app: hify-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
