# Maven Wrapper configuration
# https://maven.apache.org/wrapper/
wrapperVersion=3.3.2
distributionType=bin
distributionUrl=https://dlcdn.apache.org/maven/maven-3/3.9.16/binaries/apache-maven-3.9.16-bin.zip
