apiVersion: v1
kind: Service
metadata:
  name: hify-prometheus
  labels:
    app.kubernetes.io/name: hify-prometheus
    app.kubernetes.io/part-of: hify
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hify-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: web
